title: Digital Agriculture Application
description: >
  Ph.D. Candidate | Data Scientist
  Precision & Digital Agriculture
  Machine Learning | Deep Learning | Remote Sensing

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
