title: Digital Agriculture Application
logo: config/img/DAP.png
description: description: >
  Ph.D. Candidate | Data Scientist
  
  Precision & Digital Agriculture
  
  Machine Learning | Deep Learning | Remote Sensing
  
  
  [Email](mailto:thiagocostaagro@gmail.com) | [LinkedIn](www.linkedin.com/in/thiago-orlando-costa-barboza-5ba88213b) | [ORCiD](https://orcid.org/0000-0001-5156-2474) | [Google Scholar](https://scholar.google.com.br/citations?user=Wxg0WyMAAAAJ&hl=pt-BR) | [Lattes]( http://lattes.cnpq.br/7295109791233637)
show_downloads: True
theme: jekyll-theme-minimal
